# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  username: good
  password: bundled
  database: goods_development

test:
  adapter: postgresql
  username: good
  password: bundled
  database: goods_test

production:
  adapter: postgresql
  username: good
  password: bundled
  database: goods_production
